### ISSUE TITLE
Use case: Module Returning a String ( templating )

### ISSUE THREAD

**Issue by 59023g** [MylesBorins/proposal-top-level-await#10]
Hey all,
What would you suggest as an alternative to rendering an html string as a module ( as below ). Or rather, what am I missing architecturally to think this should be allowed? ( Yet isn't per Variant C, or seemingly the others ):

```
// home_view.js
// server 

import * as utils from '../static/utils.js'
import * as server_utils from '../utils/server_utils'

import sortBar from './sortBar'
import sideBar from '../static/sideBar'
import legList from '../static/legList'

export default async ( posts, votes, count ) => {

  let html = ``

  html += `<div class='app-left-pane'>`
  html += await sortBar( count )
  html += await legList( posts, votes )
  html += `</div>`

  html += `<div class='app-right-pane df fdr'>`
  html += await sideBar()
  html += `</div>`

  return html

}
```

**Comment by MylesBorins** [comment]
There are people thinking about this exact problem

:smile:

https://github.com/w3c/webcomponents/issues/645#issuecomment-343601237

I'm trying to wrap my head around the specific use case. The modules sortBar, sideBar, and legList. why are they being awaited?

**Comment by 59023g** [comment]
Great minds think alike!

That's a good question. Probably habit. Now that I think about it, I don't need to block here. Still curious what's happening under the hood here. 

 Thanks for pointing me to the w3c repo. I'll take a look.
