### ISSUE TITLE
[Spec] Actually grammatically allow `await` in ModuleBody

### ISSUE THREAD

**Issue by domenic** [MylesBorins/proposal-top-level-await#16]
This might just be a matter of adding [+Await] somewhere, but someone has to understand all the parametrized grammar stuff, and I at least paged that out of my brain several months ago...

A start at this in https://github.com/MylesBorins/proposal-top-level-await/tree/update-grammar (updating the non-normative note so far).

**Comment by MylesBorins** [comment]
Fixed by https://github.com/MylesBorins/proposal-top-level-await/commit/4a65922a3583bcb80a6ac993b16167f3b148d6be
