### ISSUE TITLE
Dynamic Polyfill Use Case

### ISSUE THREAD

**Issue by jkrems** [MylesBorins/proposal-top-level-await#8]
I think the following presents a problem (or at least a foot-gun) for the parallel and/or background execution of dependencies (everything but Variant A?):

```js
if (!window.Map) {
  await import('./map-polyfill');
}
```

**Comment by ljharb** [comment]
Indeed it does; you simply can’t use `import()` for polyfilling, since polyfills must run synchronously before all other code.

**Comment by zenparsing** [comment]
The current module design enforces a separation between loading (which may be async) and linking/evaluation (which is sync). Top-level await will tend to muddle that separation a bit.

The polyfill use case takes advantage of that separation, but I wonder what other use cases take advantage of it. What about bundling? With top-level await you can't really bundle things offline into a sync script.

**Comment by MylesBorins** [comment]
I've opened a PR that I believe answers this questions. (copy pasted below)

---


There currently isn't a way to dynamically import polyfills and ensure they are loaded before other code executes.

With Variant A individuals would be able to dynamically import polyfills and be guaranteed they would load before other code executes.

With Variant B there is no guarantee that other code wouldn't execute prior to the polyfill being available. Module goal scripts are [deferred by default][defer] [with execution order between multiple scripts being guaranteed](https://html.spec.whatwg.org/multipage/scripting.html#attr-script-defer). In the case of wanting to have dynamic polyfills that are guaranteed to execute prior to application code one could import polyfills as a seperate scipt tag in their html
